### ISSUE TITLE
Link resolving of deeply nested content items

### ISSUE THREAD

**Issue by b000za** [Kentico/kontent-java-packages#104]
### What went wrong?

Problem with resolving links in deeply nested content items. Imagine following situation:

Content item which has linked another content item and this item has as well linked another content item. In the last content item is a rich text where a text or word is linked to a content item (see screenshot).

<img width="730" alt="Screenshot_1" src="https://user-images.githubusercontent.com/61515908/86449355-5cae1a00-bd18-11ea-92cc-29500af9edc5.png">

So the structure would be the following:

content item -> content item -> content item -> rich text with linked text

When I inspect (debug) the rich text element that contains the link I can see that the link is there, the only problem is that the resolver doesn't notice this.

In the application a ContentLinkUrlResolver is used to resolve links. This works fine for structures that are not so deeply nested, such as: content item -> content item -> rich text with linked text (this is resolved just fine).

### Repro steps

1. Create a content item 
2. Link another content item in the previous one
3. Link another content item in the previous one as well
4. In the last content item link a content item to a text/word (see screenshot above)

### Expected behavior

Links are resolved of any depth

**Comment by petrsvihlik** [comment]
Hi @b000za ,
thanks for reporting the issue. We'll investigate it. If you have any code that you could share that could help us reproduce the issue, that would be really helpful and would speed up the resolution.

**Comment by b000za** [comment]
Hey @petrsvihlik, is there any update on this issue?

**Comment by Simply007** [comment]
Hello @b000za ,

I will try to reproduce the issue, but I have a couple of questions:

_What version of the SDK you are using?_
   * Could you try to test out beta version of the SKD ([monorepo-merge branch](https://github.com/Kentico/kontent-java-packages/tree/monorepo-merge)) - the beta is on JCenter - https://bintray.com/kentico/kontent-java-packages/kontent-delivery/4.0.0-beta.6

_Could you specify more the content model?_

Let's say there are items Item1 -> Item2 -> Item3 -> Item4

The links between Item1, Item2 and Item3 are modeled as:
* kontent items (meaning Item2 and Item3 are non-reusable content components)
  * linked as inline linked items
  * linked as inline link
* kontent component (meaning Item2 and Item3 are content items)

It would be very helpful to create a project with the model you are describing, so that we have a same input for investigation.

_Could share a code snipper how you are loading the content and how you define the resolvers?_

_Do you use Model Generator/Strongly models?_

**Comment by b000za** [comment]
@Simply007 

Hey, sorry for the late response. We recently switched to version 4.0.0-beta.6 and it seems that it works now! :) 

thx

**Comment by Simply007** [comment]
I have just released v4 https://github.com/Kentico/kontent-java-packages/releases/tag/4.0.0, there should be no difference in comparison with 4.0.0-beta.6, so feel free to make an upgrade.

Thanks for the notification @b000za.
I will close this issue for now.
